In [1]:
class FOO(object):
    
    def bar(self, message):
        print(message)

In [2]:
FOO1 = FOO().bar("Hello world!")

Hello world!


In [4]:
class FooParent:
    def bar(self, message):
        print(message)

class Foochild(FooParent):
    def bar(self, message):
        FooParent.bar(self, message)

In [5]:
Foochild().bar("Hello world again!")

Hello world again!


In [7]:
class FooParent2: # use super
    def bar(self, message):
        print(message)

class Foochild2(FooParent2):
    def bar(self, message):
        super(Foochild2, self).bar(message) 

In [8]:
Foochild2().bar("Hello world three!")

Hello world three!


In [9]:
from hyperspy.signals import Signal2D

In [10]:
dir(Signal2D)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_wrap__',
 '__call__',
 '__class__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__next__',
 '__or__',
 '__pos__',
 '__pow__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rshift__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_additional_slicing_targets',
 '_alias_signal_types',
 '_apply_function_on_data_and_remove_axis',
 '_assign_subclass',
 '_auto_

In [11]:
import h5py 

f = h5py.File("h1.hdf5", "w") # 创建一个空的hdf5文件。

d1 = f.create_dataset("dset1", (20, ), "i")　# 创建数据集，参数分别为数据集的名称，shape和元素类型

In [12]:
for key in f.keys():
    print(key)
    print(f[key].name)
    print(f[key].shape)
    print(f[key].value)

dset1
/dset1
(20,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [14]:
import numpy as np 

d1[...] = np.arange(20)  # assign value for dataset1

f["dset2"] = np.arange(15) # create another dataset and assign value

for key in f.keys(): # loop the dataset in f
    print(key)
    print(f[key].name)
    print(f[key].value)

dset1
/dset1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
dset2
/dset2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
a = np.arange(18)
f["data3"] = a 
def print_f(f):  # creat a fuction to do the stupid things
    for key in f.keys():
        print(key)
        print(f[key].name)
        print(f[key].value)

print_f(f)

data3
/data3
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
dset1
/dset1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
dset2
/dset2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
f2 = h5py.File("processed_all.hdf5")

In [22]:
g1 = f.create_group("bar") # create a group
g1["dset1"] = np.arange(10) # put three different datset
g1["dset2"] = np.arange(15)
g1["dset3"] = np.arange(20).reshape((4, 5))

def print_g(g): # create a stupid func to do the stupid things
    for key in g.keys():
        print(g)
        print(g[key].name)
        print(g[key].value)


In [23]:
print_g(g1) # show the group members

<HDF5 group "/bar" (3 members)>
/bar/dset1
[0 1 2 3 4 5 6 7 8 9]
<HDF5 group "/bar" (3 members)>
/bar/dset2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<HDF5 group "/bar" (3 members)>
/bar/dset3
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [29]:
for group in f2: # show the group in f2
    print(group)

Experiments


In [32]:
for group in f2: # show the group in f2
    print(group)
    print(type(group))

Experiments
<class 'str'>


In [34]:
print(f2.keys())

<KeysViewHDF5 ['Experiments']>


In [40]:
for group in f2: # show the group in f2
    print(group)
    

Experiments


In [43]:
def prtname(name): # read the files in the hdf5 file
    print(name)

f2.visit(prtname)

Experiments
Experiments/serialED
Experiments/serialED/axis-0
Experiments/serialED/axis-1
Experiments/serialED/axis-2
Experiments/serialED/data
Experiments/serialED/learning_results
Experiments/serialED/metadata
Experiments/serialED/metadata/General
Experiments/serialED/metadata/Processing
Experiments/serialED/metadata/Processing/apply_stretch_correction
Experiments/serialED/metadata/Processing/datfiles
Experiments/serialED/metadata/Processing/find_peaks_and_clean_images
Experiments/serialED/metadata/Processing/get_direct_beam_position
Experiments/serialED/metadata/Processing/remove_background
Experiments/serialED/metadata/Signal
Experiments/serialED/metadata/_HyperSpy
Experiments/serialED/metadata/_HyperSpy/Folding
Experiments/serialED/original_metadata
